apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: {{ .Release.Name }}
  annotations:
    kubernetes-engine.cloud.google.com/icon: >-
      data:image/png;base64,{{ .Files.Get "logo.png" | b64enc }}
    marketplace.cloud.google.com/deploy-info: '{"partner_id": "aerokube-software-public", "product_id": "moon", "partner_name": "Aerokube Software"}'
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
spec:
  descriptor:
    type: Moon
    version: {{ .Chart.Version }}
    description: |-
      Moon is an efficient Selenium browser automation solution with zero-effort maintenance.
      It comes with predefined set of images for different browsers and platforms.

      # Support
      You can get official support using the following channels:
      * [E-mail](mailto:support@aerokube.com)
      * [Telegram](https://t.me/aerokube_moon)
    maintainers:
      - name: Aerokube Software
        url: https://aerokube.com/
    links:
      - description: 'Official Documentation'
        url: https://aerokube.com/moon/latest
    notes: |-
      # Installing a license key

      Moon comes with a free license key allowing to run up to 4 parallel Selenium sessions for unlimited period of time. If you need more parallel sessions - you have to [purchase](mailto:sales@aerokube.com) a license key. A trial license key with 50 parallel sessions can be generated on our https://aerokube.com/moon/[website]. Having a license key - install it as follows:

      ```shell
      $ kubectl edit secret {{ .Release.Name }}-licensekey -n moon
      ```

      After changing the secret license key will be applied without Moon restart. How fast this will be done depends on so-called "secrets caching time". Default value is `1 minute` but can be adjusted by Kubernetes administrator.

      # Customized deployment

      This version is mainly useful for quickly trying Moon with default settings. In order to get fully customizable Moon instance - use our [official YAML manifests](https://github.com/aerokube/moon-deploy).
  info:
    - name: Moon Selenium access URL
      type: Reference
      valueFrom:
        serviceRef:
          name: "{{ .Release.Name }}-moon"
          port: {{ .Values.moon.port }}
          path: "/wd/hub"
    - name: Moon UI access URL
      type: Reference
      valueFrom:
        serviceRef:
          name: "{{ .Release.Name }}-moon"
          port: {{ .Values.moonUI.port }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Release.Name }}
  componentKinds:
  - group: v1
    kind: Service
  - group: v1
    kind: Secret
  - group: v1
    kind: ConfigMap
  - group: apps/v1
    kind: Deployment
  - group: rbac.authorization.k8s.io/v1beta1
    kind: Role
  - group: rbac.authorization.k8s.io/v1beta1
    kind: RoleBinding
