apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes-engine.cloud.google.com/icon: >-
      data:image/png;base64,{{ .Files.Get "logo.png" | b64enc }}
    marketplace.cloud.google.com/deploy-info: '{partner_id: "aerokube-software-public", product_id: "moon", partner_name: "Aerokube Software"}'
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
spec:
  descriptor:
    type: Moon
    version: '1.3'
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Release.Name }}
  componentKinds:
  - group: v1
    kind: Service
  - group: v1
    kind: Secret
  - group: v1
    kind: ConfigMap
  - group: apps/v1
    kind: Deployment
  - group: rbac.authorization.k8s.io/v1beta1
    kind: Role
  - group: rbac.authorization.k8s.io/v1beta1
    kind: RoleBinding
