---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-quota
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/component: moon
data:
  browsers.json: |
{{ .Values.browsers | toJson | indent 4 }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/component: moon
data:
  service.json: |
{{ .Values.config | toJson | indent 4 }}
